[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
internalPort = 5000
processes = ["web"]
healthCheck = "/health"

[services.web]
forceHttps = true
autoDeploy = true